FROM node:18-alpine

WORKDIR /node/app

RUN npm install -g nodemon && chmod +x $(which nodemon)

COPY ./source/package*.json ./

RUN npm install

COPY ./source ./

RUN chmod +x /node/app

CMD ["npm", "start"]
